<?php

namespace Pterodactyl\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Pterodactyl\Models\ServerCustomDomain;
use Pterodactyl\Services\Nginx\NginxDomainService;
use Symfony\Component\Process\Process;

class LunarNginxSetupCommand extends Command
{
    protected $signature = 'lunar:nginx-setup 
                            {--force : Force overwrite all existing configurations}
                            {--ssl : Also issue or renew SSL certificates for all domains}';

    protected $description = 'Configures Nginx and Certbot sudoers permissions, generates reverse proxy configurations, and verifies DNS.';

    public function __construct(private NginxDomainService $nginxService)
    {
        parent::__construct();
    }

    public function handle(): int
    {
        $this->info('=== Lunar Panel Nginx & SSL Automated Engine Setup ===');
        $this->newLine();

        // Step 1: Ensure directory exists & permissions
        $dir = $this->nginxService->getDomainsDirectory();
        $this->line("<comment>•</comment> Active Nginx configuration directory: <info>{$dir}</info>");

        $webroot = $this->nginxService->getWebroot();
        $this->line("<comment>•</comment> Certbot ACME webroot directory: <info>{$webroot}</info>");

        // On Linux as root, setup sudoers rule and file permissions
        if (PHP_OS_FAMILY !== 'Windows' && function_exists('posix_getuid') && posix_getuid() === 0) {
            // Symlink snap certbot to /usr/bin/certbot if present
            if (File::exists('/snap/bin/certbot') && !File::exists('/usr/bin/certbot')) {
                @symlink('/snap/bin/certbot', '/usr/bin/certbot');
                $this->line("<comment>•</comment> Symlinked <info>/snap/bin/certbot</info> to <info>/usr/bin/certbot</info>");
            }

            // Ensure webroot directories exist
            if (!File::isDirectory($webroot)) {
                @File::makeDirectory($webroot, 0755, true);
            }
            $challengeDir = rtrim($webroot, '/\\') . '/.well-known/acme-challenge';
            if (!File::isDirectory($challengeDir)) {
                @File::makeDirectory($challengeDir, 0755, true);
            }

            // Identify potential web server users
            $webUsers = array_unique(array_filter([
                'www-data',
                'nginx',
                'apache',
            ]));

            foreach ($webUsers as $u) {
                @chown($webroot, $u);
                @chgrp($webroot, $u);
            }
            @chmod($webroot, 0775);
            @chmod($challengeDir, 0775);

            // Configure /etc/sudoers.d/lunar-nginx
            $sudoersFile = '/etc/sudoers.d/lunar-nginx';
            $sudoersCommands = '/usr/sbin/nginx, /usr/bin/nginx, /bin/systemctl, /usr/bin/systemctl, /usr/bin/certbot, /snap/bin/certbot, /usr/local/bin/certbot, /bin/test, /usr/bin/test, /usr/bin/nsenter, /bin/nsenter, /usr/bin/systemd-run, /bin/systemd-run';

            $sudoersLines = [
                '# Generated by Lunar Panel setup engine',
            ];
            foreach ($webUsers as $u) {
                $sudoersLines[] = "{$u} ALL=(ALL) NOPASSWD: {$sudoersCommands}";
            }
            $sudoersContent = implode("\n", $sudoersLines) . "\n";

            try {
                File::put($sudoersFile, $sudoersContent);
                chmod($sudoersFile, 0440);

                // Validate with visudo if available
                $visudoCmd = File::exists('/usr/sbin/visudo') ? '/usr/sbin/visudo' : (File::exists('/sbin/visudo') ? '/sbin/visudo' : 'visudo');
                $visudo = Process::fromShellCommandline("{$visudoCmd} -cf {$sudoersFile}");
                $visudo->run();
                if ($visudo->isSuccessful()) {
                    $this->line("<comment>•</comment> Sudoers rules successfully verified and installed in <info>{$sudoersFile}</info>");
                } elseif (stripos($visudo->getErrorOutput(), 'syntax error') !== false || stripos($visudo->getOutput(), 'syntax error') !== false) {
                    $this->warn("! visudo check failed on {$sudoersFile}, removing to prevent sudo issues: " . $visudo->getErrorOutput());
                    @File::delete($sudoersFile);
                } else {
                    $this->line("<comment>•</comment> Sudoers rules installed in <info>{$sudoersFile}</info>");
                }
            } catch (\Throwable $e) {
                $this->warn("! Could not write {$sudoersFile}: " . $e->getMessage());
            }

            // Configure PHP-FPM systemd drop-in override so PHP-FPM and Certbot can write to /etc/nginx and /etc/letsencrypt
            $phpVersion = PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION;
            $fpmServices = array_unique([
                "php{$phpVersion}-fpm",
                "php-fpm",
                "php8.3-fpm",
                "php8.2-fpm",
                "php8.1-fpm",
            ]);

            $appliedOverride = false;
            foreach ($fpmServices as $fpmService) {
                $dropinDir = "/etc/systemd/system/{$fpmService}.service.d";
                $overrideFile = "{$dropinDir}/lunar.conf";

                $unitExists = File::exists("/lib/systemd/system/{$fpmService}.service") ||
                              File::exists("/etc/systemd/system/{$fpmService}.service") ||
                              File::isDirectory($dropinDir);

                if ($unitExists) {
                    if (!File::isDirectory($dropinDir)) {
                        @File::makeDirectory($dropinDir, 0755, true);
                    }

                    $overrideContent = "[Service]\nProtectSystem=false\nReadWritePaths=/etc/nginx /etc/letsencrypt /var/log/letsencrypt /var/www /tmp\n";
                    File::put($overrideFile, $overrideContent);
                    chmod($overrideFile, 0644);
                    $this->line("<comment>•</comment> Systemd override installed for <info>{$fpmService}</info> (ProtectSystem=false)");
                    $appliedOverride = true;
                }
            }

            if ($appliedOverride) {
                try {
                    $pReload = Process::fromShellCommandline('systemctl daemon-reload');
                    $pReload->run();
                    $pRestart = Process::fromShellCommandline("systemctl restart php{$phpVersion}-fpm || systemctl restart php-fpm");
                    $pRestart->run();
                    $this->line("<comment>•</comment> Reloaded systemd and restarted PHP-FPM to enable read-write access to /etc.");
                } catch (\Throwable $e) {
                    // Ignore
                }
            }

            // Ensure conf directory is writable
            if (File::isDirectory('/etc/nginx/conf.d')) {
                foreach ($webUsers as $u) {
                    @chown('/etc/nginx/conf.d', $u);
                    @chgrp('/etc/nginx/conf.d', $u);
                }
                @chmod('/etc/nginx/conf.d', 0775);
            }

            // Ensure letsencrypt permissions allow Nginx and panel inspection
            if (File::isDirectory('/etc/letsencrypt')) {
                @chmod('/etc/letsencrypt', 0755);
                if (File::isDirectory('/etc/letsencrypt/live')) {
                    @chmod('/etc/letsencrypt/live', 0755);
                }
                if (File::isDirectory('/etc/letsencrypt/archive')) {
                    @chmod('/etc/letsencrypt/archive', 0755);
                }
            }
        }

        // Step 2: Sync and re-write all domains
        $domains = ServerCustomDomain::with(['server.node', 'allocation'])->get();
        if ($domains->isEmpty()) {
            $this->info('No custom domains found in database.');
            return 0;
        }

        $this->line("<comment>•</comment> Found {$domains->count()} custom domain(s) to synchronize.");
        $rows = [];

        foreach ($domains as $domain) {
            $writeResult = $this->nginxService->writeAndReload($domain);
            $dnsResult = $this->nginxService->verifyDns($domain);

            if ($this->option('ssl')) {
                $this->line("<comment>•</comment> Requesting SSL certificate for: <info>{$domain->domain}</info>...");
                $sslResult = $this->nginxService->provisionSsl($domain);
                if ($sslResult['success']) {
                    $this->line("  <info>✓ SSL Provisioned successfully.</info>");
                } else {
                    $this->warn("  <comment>! SSL Provisioning failed: " . ($sslResult['error'] ?? 'Unknown error') . "</comment>");
                }
            }

            $domain->refresh();

            $rows[] = [
                $domain->id,
                $domain->domain,
                $domain->protocol,
                $domain->nginx_status,
                $domain->dns_status,
                $domain->ssl_status,
                $writeResult['success'] ? 'OK' : 'Error',
            ];
        }

        $this->table(
            ['ID', 'Domain', 'Protocol', 'Nginx Status', 'DNS Status', 'SSL Status', 'Config Write'],
            $rows
        );

        $this->newLine();
        $this->info('✓ All custom domains synchronized successfully with Nginx reverse proxy.');

        return 0;
    }
}
